#!/usr/bin/env bash
# Link the workspace's canonical snippet files into the editor's User (global)
# snippets dir so they work no matter which folder is opened as the workspace
# root -- in particular a single contest dir (src/contest/<c>/), which is how
# pahcer-UI expects to be used.
#
# The server dir (~/.cursor-server / ~/.vscode-server) is NOT a persisted
# volume, so this must run on every attach, like install_pahcer_ui.sh.
#
# Canonical source: $WORKSPACE_FOLDER/.vscode/*.code-snippets
#   - rust.code-snippets          : generated by cargo_snippet.sh from src/lib
#   - my-hand-rust.code-snippets  : hand-written
# Symlinks (not copies) mean edits to the source are picked up on the next
# window reload with no re-sync step.
set -uo pipefail

: "${WORKSPACE_FOLDER:?WORKSPACE_FOLDER is not set}"
src_dir="$WORKSPACE_FOLDER/.vscode"

shopt -s nullglob
sources=("$src_dir"/*.code-snippets)
shopt -u nullglob

if [[ ${#sources[@]} -eq 0 ]]; then
    echo "[snippets] no *.code-snippets in $src_dir; nothing to link." >&2
    exit 0
fi

linked_any=0
for server_dir in "$HOME/.cursor-server" "$HOME/.vscode-server"; do
    [[ -d "$server_dir" ]] || continue
    dest_dir="$server_dir/data/User/snippets"
    mkdir -p "$dest_dir"
    for f in "${sources[@]}"; do
        ln -sfn "$f" "$dest_dir/$(basename "$f")"
    done
    echo "[snippets] linked ${#sources[@]} file(s) into $dest_dir"
    linked_any=1
done

if [[ "$linked_any" -eq 0 ]]; then
    echo "[snippets] no server dir found (~/.cursor-server, ~/.vscode-server); nothing linked." >&2
    exit 0
fi

echo "[snippets] done. Reload the window (Developer: Reload Window) to pick them up."
